### ISSUE TITLE
Windows Install Issue

### ISSUE THREAD

**Issue by mrobideau** [andrefs/node-sb-builder#1]
Running into an issue when running

`npm install -g sb-builder`

npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

**Full stack trace**

$ npm install -g sb-builder
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN installMany node-pre-gyp was bundled with mp3info@0.0.10, but bundled package wasn't found in unpacked tree
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'

> mp3info@0.0.10 install C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Source compile required: 404 status code downloading tarball
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild --configuration=Release --module_name=bindings --version=0.0.10 --patch=10 --runtime=node --node_abi=node-v46 --platform=win32 --arch=x64 --target_arch=x64 --module_main=./index.js --host=https://mp3info.s3.amazonaws.com/ --module_path=C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\build\Release --remote_path=./Release/ --package_name=bindings-v0.0.10-node-v46-win32-x64.tar.gz --staged_tarball=build\stage\Release\bindings-v0.0.10-node-v46-win32-x64.tar.gz --hosted_path=https://mp3info.s3.amazonaws.com/Release/ --hosted_tarball=https://mp3info.s3.amazonaws.com/Release/bindings-v0.0.10-node-v46-win32-x64.tar.gz )  else (node "" rebuild --configuration=Release --module_name=bindings --version=0.0.10 --patch=10 --runtime=node --node_abi=node-v46 --platform=win32 --arch=x64 --target_arch=x64 --module_main=./index.js --host=https://mp3info.s3.amazonaws.com/ --module_path=C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\build\Release --remote_path=./Release/ --package_name=bindings-v0.0.10-node-v46-win32-x64.tar.gz --staged_tarball=build\stage\Release\bindings-v0.0.10-node-v46-win32-x64.tar.gz --hosted_path=https://mp3info.s3.amazonaws.com/Release/ --hosted_tarball=https://mp3info.s3.amazonaws.com/Release/bindings-v0.0.10-node-v46-win32-x64.tar.gz )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--configuration=Release" "--module_name=bindings" "--version=0.0.10" "--patch=10" "--runtime=node" "--node_abi=node-v46" "--platform=win32" "--arch=x64" "--target_arch=x64" "--module_main=./index.js" "--host=https://mp3info.s3.amazonaws.com/" "--module_path=C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\build\Release" "--remote_path=./Release/" "--package_name=bindings-v0.0.10-node-v46-win32-x64.tar.gz" "--staged_tarball=build\stage\Release\bindings-v0.0.10-node-v46-win32-x64.tar.gz" "--hosted_path=https://mp3info.s3.amazonaws.com/Release/" "--hosted_tarball=https://mp3info.s3.amazonaws.com/Release/bindings-v0.0.10-node-v46-win32-x64.tar.gz"
gyp ERR! cwd C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd rebuild --configuration=Release --module_name=bindings --version=0.0.10 --patch=10 --runtime=node --node_abi=node-v46 --platform=win32 --arch=x64 --target_arch=x64 --module_main=./index.js --host=https://mp3info.s3.amazonaws.com/ --module_path=C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\build\Release --remote_path=./Release/ --package_name=bindings-v0.0.10-node-v46-win32-x64.tar.gz --staged_tarball=build\stage\Release\bindings-v0.0.10-node-v46-win32-x64.tar.gz --hosted_path=https://mp3info.s3.amazonaws.com/Release/ --hosted_tarball=https://mp3info.s3.amazonaws.com/Release/bindings-v0.0.10-node-v46-win32-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\node_modules\node-pre-gyp\lib\util\compile.js:76:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.10586
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Michael\AppData\Roaming\npm\node_modules\sb-builder\node_modules\mp3info
node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.5.5
node-pre-gyp ERR! not ok
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "sb-builder"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! mp3info@0.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mp3info@0.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the mp3info package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mp3info
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls mp3info
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cygwin\home\Michael\npm-debug.log

**Comment by pmlnunes** [comment]
I'm also getting this error

**Comment by andrefs** [comment]
Hi there,

I'm guessing the problem is the `mp3info` module, which was last published 5 years ago.
This should probably be replaced by something more up to date.

As far as I remember, the last time I used `node-sb-builder` it would only run with Node versions v0.10 or older, and `mp3info` was the main culprit.

Currently I don't have a lot of free time to debug this issue. The best I can do is to promise that I'll look into this whenever I find some free time. Other than that, I'm willing to accept pull requests :)
